### PR TITLE
update Rac3-Truck Readme

### PR DESCRIPTION
**Pull request by AntoniLuongPham**
Dear @laurensvalk and @dlech,

Here are my changes for Rac3 Truck.

Thank you very much!

Antoni

### CODE REVIEW

**Comment by AntoniLuongPham** [comment]
Dear @laurensvalk and @dlech,

I updated my Rac3-Truck README further and checked with my dad @TheVinhLuong102.
It is now ready for your review!

I found my video of with the Pybricks code.
Thank you very much!

Antoni

**Comment by TheVinhLuong102** [comment]
Hi @laurensvalk and @dlech,

@AntoniLuongPham and I have followed the BOOST Auto Builder README and updated those for Rac3 Truck, RoboDoz3r and Wack3m to a similar format.

Re: the videos, we have @AntoniLuongPham's YouTube videos for Rac3 Truck and RoboDoz3r that show PyBricks code (instead of EV3Dev2). The presentational eloquence is, understandably, borderline passable but not great :) Please do consider if these are good enough for your website. If they are not, we can use the LEGO RobotMak3r Studio videos instead for now, and try to re-film and re-submit Antoni's presentations later the next time he and his sister build these models.

Thank you.

Vinh

**Comment by laurensvalk** [comment]
Thank you all for all the hard work!

It may take us a while to process everything and settle on a good format for images, video, and descriptions. I apologize for changing things around a lot :)

For now I've merged all submissions as-is, so we can all get a proper preview of how it looks on the website. With this in place, you may find it easier to go through existing content pages, and make changes and fixes as needed. Hope this helps. Please stay tuned :)

**Comment by TheVinhLuong102** [comment]
@laurensvalk,

Thank you so much!

We love the changes you've been making to publish the projects to the website, and totally understand that everyone is discovering new technical requirements while doing this.

I realized the significance of these changes so instructed @AntoniLuongPham and @ArianaLuongPham to pause on writing new programs and focus instead on refactoring the existing ones. It's been a great experience for them -- learning that documenting and presenting is just as much hard work as building the robots and coding the programs. :)

Vinh

**Comment by TheVinhLuong102** [comment]
@dlech and @laurensvalk, the PyBricks website looks absolutely fabulous -- the embedded images & videos are very engaging to young robot makers!

Now that we see the content rendered on the site, we'll refine the code & docs further. :)

Btw @dlech I see that you're limiting the code block width to 70 chars. Is this parameter pretty much fixed going forward? If yes, we'll refactor the code to limit the line length from 79 to 70 -- so that the viewers will need no horizontal scrolling.

Vinh

**Comment by dlech** [comment]
Yes, if you can run `flake8` on the code and fix any errors/warnings, that will help us keep a somewhat consistent code style among projects.

**Comment by TheVinhLuong102** [comment]
@dlech we'll happily do! @ArianaLuongPham shall champion this and perform some good deeds. ;)

**Comment by TheVinhLuong102** [comment]
@dlech another thing we should think about is how to display the code for robots with multiple variants / games. For example, EV3 Tracker and the Inventor Core robots have 5-10 different tasks, each of which is interesting on its own. However, displaying all the programs at the same time on the same page is overwhelming to the viewer.

Maybe we should consider a collapse/expand mechanism?

**Comment by dlech** [comment]
For those, we might want to just show the first task as an example and just mention that there are more if you download the entire project.

Another thing while you are cleaning things up is that we should be using `#` comments instead of `"""`. MicroPython has a limitation that doc comment strings actually allocate memory even though they are not used for anything.

**Comment by dlech** [comment]
For EV3 (and only EV3), we will need to make a button to download the entire project folder anyway, so if you just want to show snippets of interesting code instead of the entire file on those pages, that is fine too.

**Comment by dlech** [comment]
> Another thing while you are cleaning things up is that we should be using `#` comments instead of `"""`. MicroPython has a limitation that doc comment strings actually allocate memory even though they are not used for anything.

Although since we don't run .py files on the device other that EV3 which has plenty of memory, it probably isn't really a problem.

**Comment by TheVinhLuong102** [comment]
@dlech no problem, since @AntoniLuongPham and @ArianaLuongPham will be scrubbing the programs & docs another round to optimize the look & feel on the website, we'll take all of the ^ suggestions into account for each refactoring exercise. :)

**Comment by TheVinhLuong102** [comment]
@dlech, @laurensvalk, for the community/fan creations, shall we explicitly credit the robot designers (e.g. @laurensvalk, Martyn Boogaarts, etc.) on the website too?

Right now it appears as if the Pybricks code project submitter is also the creator of the design.

Vinh

**Pull request merged**
