### PR TITLE
Update El3ctric Guitar readme

### PR DESCRIPTION
**Pull request by AntoniLuongPham**
Dear @laurensvalk and @dlech,

Here are my changes for El3ctric Guitar.

Thank you very much!

Antoni

### CODE REVIEW

**Comment by laurensvalk** [comment]
Thanks so much for submitting all those changes!

It seems that some of the remaining pull requests could not be merged directly. Is this something you want to look into?

Just let us know if we can help :smiley:

**Comment by TheVinhLuong102** [comment]
@laurensvalk,

Yes, @AntoniLuongPham got some git-branching mixed up during his dev. We'll resolve the conflicts for the remaining 5 PRs and inform you later today. :)

Vinh

**Comment by AntoniLuongPham** [comment]
Dear @laurensvalk,

My dad helped me to resolved the conflicts the five robots and are now good.

Thank you for merging my code!

Antoni

**Comment by TheVinhLuong102** [comment]
Hi @laurensvalk,

For the remaining 5 EV3 Home Bonus PRs, I think the merging sequence can be:

1. Robodoz3r
2. El3ctric Guitar (this one)
3. Mr. B3am
4. Kraz3
5. EV3 Game

Sorry for the complexity! In future rounds, I'll help @AntoniLuongPham get the branching correct from the beginning.

Vinh

**Pull request merged**
