### PR TITLE
add EV3 Game program

### PR DESCRIPTION
**Pull request by AntoniLuongPham**
Dear @laurensvalk and @dlech,

I am submitting my EV3 game program for your review.

The robot code is hard but it is fun to play with.

The robot code is very long and has a lot of functions so it took me a lot of time.

My dad helped me with some math and variables. He found a big bug in the execute_move function and fixed it for me.

Thank you very much! :)

Antoni

### CODE REVIEW

**Comment by laurensvalk** [comment]
Thanks Antoni, this is great! I've merged it :tada: 

I noticed in some of your programs, `ev3_brick` is added as a class attribute. There's nothing wrong with that per se, but it might not be needed if you use the EV3 brick methods directly.

For example:

```python
ev3_game.ev3_brick.light.on(color=Color.GREEN)
```
might be easier to understand as:

```python
ev3.light.on(color=Color.GREEN)
```

because then users will quickly see that this is a standard function.

I think you might have taken apart most of the models already, so don't worry about it for these pull requests :)

**Comment by TheVinhLuong102** [comment]
Hi @laurensvalk,

Do you mean we should split the EV3Brick out as a separate entity from the robot? We have been using the "has a" pattern re: the EV3Brick, after our discussion here https://github.com/pybricks/pybricks-projects/pull/7#issuecomment-679268461. Do you prefer the `ev3` brick being outside the class instance instead?

**Comment by laurensvalk** [comment]
I think it's fine to leave these programs unchanged, it's just an idea for future projects. The "has a" pattern, is certainly useful for methods like these, which are useful indeed:

```python
    def display_level(self):
        self.ev3_brick.screen.clear()

        self.ev3_brick.screen.print('Level {}'.format(self.level))

        wait(300)
```

It was mainly a thought for the case where the ev3 mehods are currently accessed directly through the attribute. Part of it is abstracted as above, and part of it is not:


```python
        if correct_choice:
            ev3_game.ev3_brick.light.on(color=Color.GREEN)

            ev3_game.ev3_brick.speaker.play_file(file=SoundFile.CHEERING)
```

Another way to do it would be something like:

```python
        if correct_choice:
            ev3_game.show_correct_choice()
```

Again, don't worry about it, it's not a requirement at all, just an idea. :)

**Comment by TheVinhLuong102** [comment]
@laurensvalk I see -- it's about the abstraction levels for the robot actions then. We'll look for opportunities for such further abstractions when programming the new robots or when refactoring the existing then.

The approach @AntoniLuongPham and I have been taking is as follows:

0. As-Is Translation: We first look at the original blocks-based code (Scratch for Home, LabVIEW for Home Bonus) and translate the code as faithfully as possible to Python (PyBricks/EV3Dev) to see if it works. In particular, when the original author has "My Blocks", we first translate those My Blocks to separate class methods. The original author's main program is usually first parked under our `def main`, `if __name__ == '__main__'` or in a separate script. 

1. Parameter Tuning: adjust parameters if the initial as-is translation of the Scratch/LabVIEW code doesn't work -- e.g. because of Python's different processing time.

2. Refactoring: we try to identify opportunities for abstracting certain code sections to class methods (similar to the case you pointed out above) or shorten the code using the more powerful Python APIs. There are definitely opportunities we have missed. Let us relook at the programs during the holiday season and do a round of further refactoring. :)

**Pull request merged**
