### PR TITLE
add Official Home Edition pybricks programs

### PR DESCRIPTION
**Pull request by TheVinhLuong102**
@dlech @laurensvalk I have managed use PyBricks 2.0 to program certain Home-Edition robots, and I must say it's a fabulous programming experience! :) Thank you for initiating and driving this Pythonic API.

I notice that this PyBricks demo/example programs repo has got the Education Edition programs populated, but no Home Edition ones yet. Would you welcome contribution from community members like me to complete those? If yes, do you have certain standards for pull requests?

I have pushed a folder for Ev3rstorm here for your consideration and further guidance.

Many thanks again. :)

### CODE REVIEW

**Comment by laurensvalk** [comment]
Thank you for your contributions so far!

We're still in the process of establishing standards for projects - see also https://github.com/pybricks/support/issues/94, so it may take a bit of time before we review and merge this.

**Comment by TheVinhLuong102** [comment]
@laurensvalk  thank you. Yes, having standards defined for the official LEGO Education / PyBricks tutorials would provide very helpful clarity to community contributors. :)

My son @AntoniLuongPham and I are having a summer-long endeavor of building and programming all of the Home Edition core & fan robots with Python. This month or by early August, we would likely be done with the 5 core ones, the PyBricks code for which will be in this PR for your review and feedback. After that, we plan to embark on the more complex fan robots and contribute our PyBricks code in a separate PR, since we don't know how long those 12 robots will take us.

Btw, @AntoniLuongPham is 6-year old and he declares PyBricks to be his favorite textual API for EV3 (over the Swift Playground EV3 Sandbox and EV3Dev2), which speaks to the friendliness and ease of use of PyBricks. :) Since he has enjoyed this excellent tool, I encourage him to contribute back the code for the robots he builds -- obviously with lots of my help for directory layouts and docstrings.

**Comment by dlech** [comment]
Thanks for the continued work on this. I haven't looked at it in detail yet, but one high-level comment I have is that multiple-inheritance is quite tricky in MicroPython, so it would be nice if we could avoid using it.

**Comment by TheVinhLuong102** [comment]
@dlech that's interesting, we were unaware of that. May we have some links to this MicroPython issue so that I can understand it a bit better? Actually @AntoniLuongPham and I have used multiple inheritance in many `micropython` (EV3Dev2) and `pybricks-micropython` programs and have not encountered any notable problems. 

Regarding this PR, there are 3 instances of multiple inheritance:
- `class Ev3rstorm(RemoteControlledTank, EV3Brick)`
- `class Gripp3r(RemoteControlledTank, EV3Brick)`
- `class Track3r(RemoteControlledTank, EV3Brick)`

Since PyBricks doesn't have a utility `RemoteControlledTank`, we have coded such a class and coped-and-pasted it across these programs.

Do you prefer fixing the multiple-inheritance usage by:
1) moving the `RemoteControlledTank` code into the robot classes; or
2) use `self.ev3_brick = EV3Brick()` ("has a") instead of inheriting `EV3Brick` ("is a")?

Thank you @dlech!

**Comment by dlech** [comment]
> May we have some links to this MicroPython issue so that I can understand it a bit better?

- Some of the differences from CPython are documented here: https://docs.micropython.org/en/latest/genrst/core_language.html#classes.
- Open issues related to multiple inheritance are here: https://github.com/micropython/micropython/search?q=%22multiple+inheritance%22&state=open&type=Issues

Basic usage works as you have seen, but there are hidden surprises that can cause problems for the unsuspecting user.



>     1. moving the `RemoteControlledTank` code into the robot classes; or

Since the code is already duplicated this might make more sense.

**Comment by laurensvalk** [comment]
First of all, thanks for the contributions. I hope you and your son have had a lot of fun working on this!

A few notes and questions at first glance:
- It appears that the project settings are missing. Our intention with this repository is that each project can be used independently. Perhaps you can have a look at how the education robot projects are structured.
- In the same vain, having `if __name__ == '__main__':` is not required. It can certainly be useful if you want to make the classes reuable. But if that's the goal, it would be nice to demonstrate it by having, for example, a `gripper.py` with the class. And then a `main.py` that imports, initializes and calls it. [Here](https://github.com/pybricks/pybricks-projects/tree/e9735b2db0abf3ef004ed2620a93d3ac4d24d617/snippets/ev3/buttons_quickstart) is one example of such a multi-file project (in this case with a function instead of a class, but the same applies.)

> Do you prefer fixing the multiple-inheritance usage by:
> 
> moving the RemoteControlledTank code into the robot classes; or
> use self.ev3_brick = EV3Brick() ("has a") instead of inheriting EV3Brick ("is a")?

I suppose both could work. In general, though, EV3STORM isn't an EV3 Brick. It is a robot that has an EV3 Brick, but there's definitely multiple styles to achieve the same goal :)

Once you're happy with your final code, would you mind if we made some changes to the commits to match the style of this repository?

**Comment by TheVinhLuong102** [comment]
@laurensvalk I fully agree that "has-a" is a much more natural and understandable way for each Robot to declare the EV3Brick. We have hence revised the code to use `self.ev3_brick = EV3Brick()` instead of inheriting `EV3Brick`.

Regarding the projects' directory layouts:

- We shall work on the VSCode project settings, following the Education project settings, as you recommended

- We notice that each of the Education robots at https://github.com/pybricks/pybricks-projects/tree/master/official_models/ev3/education_core seems to have only one `main.py` file, whose contents is rendered on the documentation site at, say, https://pybricks.github.io/ev3-micropython/examples/color_sorter.html. Do we need to comply with this pattern as well to make it easy for you to render the docs? We initially planned to write code in a more modularized manner, but after noticing this everything-in-`main.py` pattern we have attempted to match it. Please let us know. :)

P.S.: @AntoniLuongPham has enjoyed his EV3 programming activity tremendously throughout the 2nd half of his Kindergarten year (learned-from-home because of Covid) as well as the whole summer (without our usual road trips). You can see he how excited he is when sharing about his programmed creations on [YouTube](https://www.youtube.com/channel/UCfGcT7xMNn2UIZmKP1yO8FA), including the official models as well as some weird stuff he thought up! :) @AntoniLuongPham really wants to rush through all the robots as quickly as possible, but I've made him slow down and take the necessary time to try out all the various APIs (PyBricks, EV3Dev, Swift Playground) to learn deeper programming patterns.

@dlech @laurensvalk you can also see that the EV3Dev Browser on VSCode is a fantastic medium that's very easy to use even for young programmers -- huge, huge thanks to you and other leaders in the community!!

**Comment by laurensvalk** [comment]
Thanks for the updates!

On [this branch](https://github.com/pybricks/pybricks-projects/commits/luong) I've squashed some of the commits together to leave one commit per model (and so both of you will still be in the main git history).

Could you verify that this looks allright to you? All the files should be there, but let me know if I missed anything.

**Comment by laurensvalk** [comment]
After that, it would also be really great if you could address the following style notes (obtained using flake8):

```
./official_models/ev3/home/track3r/main.py:24:89: E501 line too long (103 > 88 characters)
./official_models/ev3/home/track3r/main.py:32:89: E501 line too long (89 > 88 characters)
./official_models/ev3/home/track3r/main.py:34:89: E501 line too long (90 > 88 characters)
./official_models/ev3/home/track3r/main.py:40:1: W293 blank line contains whitespace
./official_models/ev3/home/track3r/main.py:41:1: W293 blank line contains whitespace
./official_models/ev3/home/track3r/main.py:42:5: E303 too many blank lines (2)
./official_models/ev3/home/track3r/main.py:46:9: E125 continuation line with same indent as next logical line
./official_models/ev3/home/track3r/main.py:47:89: E501 line too long (94 > 88 characters)
./official_models/ev3/home/track3r/main.py:107:5: E303 too many blank lines (2)
./official_models/ev3/home/track3r/main.py:114:89: E501 line too long (91 > 88 characters)
./official_models/ev3/home/track3r/main.py:122:1: W293 blank line contains whitespace
./official_models/ev3/home/track3r/main.py:123:5: E303 too many blank lines (2)
./official_models/ev3/home/track3r/main.py:138:18: W291 trailing whitespace
./official_models/ev3/home/track3r/main.py:140:9: E125 continuation line with same indent as next logical line
./official_models/ev3/home/track3r/main.py:146:27: W291 trailing whitespace
./official_models/ev3/home/track3r/main.py:149:1: W293 blank line contains whitespace
./official_models/ev3/home/track3r/main.py:150:89: E501 line too long (90 > 88 characters)
./official_models/ev3/home/track3r/main.py:154:5: E303 too many blank lines (2)
./official_models/ev3/home/track3r/main.py:156:1: W293 blank line contains whitespace
./official_models/ev3/home/track3r/main.py:170:1: W293 blank line contains whitespace
./official_models/ev3/home/track3r/main.py:174:9: E125 continuation line with same indent as next logical line
./official_models/ev3/home/track3r/main.py:186:89: E501 line too long (90 > 88 characters)
./official_models/ev3/home/track3r/main.py:190:5: E303 too many blank lines (2)
./official_models/ev3/home/track3r/main.py:221:5: E303 too many blank lines (2)
./official_models/ev3/home/track3r/main.py:242:9: E125 continuation line with same indent as next logical line
./official_models/ev3/home/track3r/main.py:249:1: W293 blank line contains whitespace
./official_models/ev3/home/track3r/main.py:250:5: E303 too many blank lines (2)
./official_models/ev3/home/gripp3r/main.py:24:89: E501 line too long (103 > 88 characters)
./official_models/ev3/home/gripp3r/main.py:32:89: E501 line too long (89 > 88 characters)
./official_models/ev3/home/gripp3r/main.py:34:89: E501 line too long (90 > 88 characters)
./official_models/ev3/home/gripp3r/main.py:40:1: W293 blank line contains whitespace
./official_models/ev3/home/gripp3r/main.py:41:1: W293 blank line contains whitespace
./official_models/ev3/home/gripp3r/main.py:42:5: E303 too many blank lines (2)
./official_models/ev3/home/gripp3r/main.py:46:9: E125 continuation line with same indent as next logical line
./official_models/ev3/home/gripp3r/main.py:47:89: E501 line too long (94 > 88 characters)
./official_models/ev3/home/gripp3r/main.py:107:5: E303 too many blank lines (2)
./official_models/ev3/home/gripp3r/main.py:115:89: E501 line too long (91 > 88 characters)
./official_models/ev3/home/gripp3r/main.py:129:5: E303 too many blank lines (2)
./official_models/ev3/home/gripp3r/main.py:150:89: E501 line too long (90 > 88 characters)
./official_models/ev3/home/gripp3r/main.py:154:5: E303 too many blank lines (2)
./official_models/ev3/home/gripp3r/main.py:163:1: W293 blank line contains whitespace
./official_models/ev3/home/r3ptar/main.py:51:5: E303 too many blank lines (2)
./official_models/ev3/home/r3ptar/main.py:86:5: E303 too many blank lines (2)
./official_models/ev3/home/r3ptar/main.py:100:89: E501 line too long (90 > 88 characters)
./official_models/ev3/home/r3ptar/main.py:104:5: E303 too many blank lines (2)
./official_models/ev3/home/r3ptar/main.py:109:5: E303 too many blank lines (2)
./official_models/ev3/home/ev3rstorm/main.py:26:89: E501 line too long (103 > 88 characters)
./official_models/ev3/home/ev3rstorm/main.py:34:89: E501 line too long (93 > 88 characters)
./official_models/ev3/home/ev3rstorm/main.py:36:89: E501 line too long (94 > 88 characters)
./official_models/ev3/home/ev3rstorm/main.py:42:1: W293 blank line contains whitespace
./official_models/ev3/home/ev3rstorm/main.py:43:1: W293 blank line contains whitespace
./official_models/ev3/home/ev3rstorm/main.py:44:5: E303 too many blank lines (2)
./official_models/ev3/home/ev3rstorm/main.py:48:9: E125 continuation line with same indent as next logical line
./official_models/ev3/home/ev3rstorm/main.py:49:89: E501 line too long (94 > 88 characters)
./official_models/ev3/home/ev3rstorm/main.py:109:5: E303 too many blank lines (2)
./official_models/ev3/home/ev3rstorm/main.py:117:89: E501 line too long (91 > 88 characters)
./official_models/ev3/home/ev3rstorm/main.py:121:1: W293 blank line contains whitespace
./official_models/ev3/home/ev3rstorm/main.py:129:5: E303 too many blank lines (2)
./official_models/ev3/home/ev3rstorm/main.py:131:89: E501 line too long (98 > 88 characters)
./official_models/ev3/home/ev3rstorm/main.py:136:1: W293 blank line contains whitespace
./official_models/ev3/home/ev3rstorm/main.py:137:5: E303 too many blank lines (2)
./official_models/ev3/home/ev3rstorm/main.py:143:89: E501 line too long (92 > 88 characters)
./official_models/ev3/home/ev3rstorm/main.py:150:89: E501 line too long (107 > 88 characters)
./official_models/ev3/home/ev3rstorm/main.py:161:89: E501 line too long (107 > 88 characters)
./official_models/ev3/home/ev3rstorm/main.py:169:5: E303 too many blank lines (2)
./official_models/ev3/home/ev3rstorm/main.py:171:13: E124 closing bracket does not match visual indentation
./official_models/ev3/home/spik3r/main.py:46:5: E303 too many blank lines (2)
./official_models/ev3/home/spik3r/main.py:72:89: E501 line too long (90 > 88 characters)
./official_models/ev3/home/spik3r/main.py:74:1: W293 blank line contains whitespace
./official_models/ev3/home/spik3r/main.py:75:1: W293 blank line contains whitespace
./official_models/ev3/home/spik3r/main.py:76:5: E303 too many blank lines (2)
./official_models/ev3/home/spik3r/main.py:94:5: E303 too many blank lines (2)
./official_models/ev3/home/spik3r/main.py:113:5: E303 too many blank lines (2)
./official_models/ev3/home/spik3r/main.py:118:1: W293 blank line contains whitespace
```

**Comment by laurensvalk** [comment]
And you can just make the changes on your own branch - I'll combine them later.

**Comment by TheVinhLuong102** [comment]
@laurensvalk thank you. To follow up, we have done the following:

- Refactor the 5 programs to fix the linters' warnings

- To make it easy for the Official Models' examples to render on your doc site, we are following how you've done the Education Edition programs and hence still keeping the code for each robot in one single `main.py` file (instead of modularizing the code into, say, for Ev3rstorm, `rc_tank_util.py`, `ev3rstorm.py` and `main.py`)

We have the following questions re: the VSCode project settings checked into GitHub:

- Should be set the `python.linting.enabled` config as `true` instead of `false`, given that you want consistency across the submitted programs' styles? If yes, which linter(s) should we enable?
- Maybe we can add `editor.rulers: [79]` as well to show the line-length-limit ruler in the editor.

**Comment by laurensvalk** [comment]
Great, thanks!

> To make it easy for the Official Models' examples to render on your doc site,

Note that the [documentation](https://docs.pybricks.com/en/latest/) does not render any programs, it just links to the projects repository, so there is no objection against multi-file projects. Single programs are fine too though.

> We have the following questions re: the VSCode project settings checked into GitHub:

Let's keep them at the default values for new projects. Perhaps we need to update the settings for the Education models too, then.

**Comment by TheVinhLuong102** [comment]
@laurensvalk re: the doc site, I'm a little confused whether https://pybricks.github.io/ev3-micropython (which is linked from https://education.lego.com/en-us/support/mindstorms-ev3/python-for-ev3, and which renders the `main.py` code, e.g. https://pybricks.github.io/ev3-micropython/examples/color_sorter.html) or https://docs.pybricks.com is the site to go to. Is one of them going to be deprecated/removed?

**Comment by laurensvalk** [comment]
The former documentation is only for EV3. LEGO education has tested and approved it for their use case. This includes the EV3 education programs. That documentation version will probably stay the same for a long time, providing a consistent experience for teachers and students. It gets updated only if errors are found.

The second link is the main open source Pybricks documentation. This includes EV3 as well as all the other programmable hubs. It continues to evolve as we add more features to Pybricks over time and work towards the next release.

**Comment by TheVinhLuong102** [comment]
@laurensvalk ah, I understand now, thanks for the clarification.

If that's the case, let us refactor these programs a bit further to make them more modularized. Will let you know when done.

**Comment by TheVinhLuong102** [comment]
@laurensvalk we have completed the refactoring. :)
- for those robots with a drive base, we've created `rc_tank_util.py`, which can be copied and pasted for use in other cases
- for Track3r, we've created 1 file for each variant, e.g. `track3r_with_biblade_spinner.py`, `track3r_with_heavy_hammer.py`
- we've also updated the VSCode settings to enable linting (which is the default)

**Comment by laurensvalk** [comment]
I just merged it. Thanks for the hard work!

**Comment by TheVinhLuong102** [comment]
@laurensvalk @dlech thank you very much for your review and merge!

@AntoniLuongPham and I have already started on the Home Bonus robots and shall submit new PRs -- the first one being for Dinor3x -- soon. :)

Many thanks again, looking forward to new PyBricks developments!

**Pull request merged**
