### PR TITLE
add Inventor set Tricky programs

### PR DESCRIPTION
**Pull request by AntoniLuongPham**
Dear @laurensvalk and @dlech,

Happy New Year! 🎆 

I got the Mindstorms Inventor set from Santa.

I wrote a letter to Santa saying I like lego. So when we saw the big box under the present tree my dad thought it was Duplo, but when I open it it was the Inventor set!

I feel happy to submit my first program this year for your review.

I had played soccer before so I did the soccer program first.

Thank you very much! 

Antoni 🎁 !

### CODE REVIEW

**Comment by TheVinhLuong102** [comment]
Hi @laurensvalk and @dlech,

As @AntoniLuongPham shared above, Santa was incredibly kind and understanding this season! His sister Ariana also got a colorful SPIKE Prime set. I was amazed myself! ;)

@AntoniLuongPham and I are playing with all the new APIs -- LEGO's Scratch and Python APIs, and PyBricks. Since he already knows PyBricks (he can actually code much PyBricks without reading the docs now :) ), it is easier for him to try writing the PyBricks programs first. I'm helping him out with the PyBricksDev CLI setup and the code.pybricks.com interface.

Since this new SPIKE-based system is different from EV3, I've asked @AntoniLuongPham to open this PR with one program first, so that we have something concrete in front for you to review and instruct us re: the standards for these new programs. Right now I have a few questions:

- is `sets/spike/inventor/` an appropriate path for this set? In my mental model, "spike" is at the same level as "ev3" (indicating the system), while "inventor" is at the same level as "home" / "home_bonus" / "education_core" / "education_extension"

- What should we write in READMEs?

- Do we need auxiliary files such as .GitIgnore and the VSCode settings/configs files?

Above are some obvious considerations I would like to check with you on. Please also let us have comments/instructions on other aspects of these new PRs that you think of.

Thank you and Happy New Year!

Vinh

**Comment by dlech** [comment]
Happy new year. We're glad you are still having fun with robots and Pybricks.



>     * In my mental model, "spike" is at the same level as "ev3"

Actually, "Prime" and "Inventor" are on the same level as "EV3" while "SPIKE" is on the same level as "MINDSTORMS".

>     * What should we write in READMEs?

Anything that someone who has not used Pybricks very much might need to know about using your program.

>     * Do we need auxiliary files such as .GitIgnore and the VSCode settings/configs files?

No, these are not needed for Powered Up hub programs.

**Comment by laurensvalk** [comment]
Thanks for submitting this! I will get back to you as soon as possible, but certainly this upcoming week.

**Comment by TheVinhLuong102** [comment]
Thank you @dlech and @laurensvalk!

We will gradually add the other games/programs for Tricky to this PR, in parallel to your review and standard-setting for the Inventor set. :)

I have also observed some things that do not work as expected yet, and will open Issues to track those bugs.

Vinh

**Comment by TheVinhLuong102** [comment]
@laurensvalk @dlech, I've got @AntoniLuongPham to update the Tricky Basic and Tricky Playing Soccer programs after the recent Sensor & Motor bug fixes.

His school semester has started, so we're probably gonna take a while with other Tricky variations. Would you like to review the current PR with these 2 programs first, so that we can set these as a standard for subsequent PRs?

**Comment by laurensvalk** [comment]
Thanks for the updates.

> Would you like to review the current PR with these 2 programs first, so that we can set these as a standard for subsequent PRs?

That sounds like a good plan :+1:.

**Comment by laurensvalk** [comment]
I've had a look at the tricky soccer example. Very nice!

A couple of tips and tricks in terms of features:
- In `reset_kicker_motor`, I'm guessing you are using `run_time` to put the motor all the way to one end. You might want to consider `run_until_stalled` for this purpose with an appropriate `duty_limit` setting.
- Instead of `hub.light.on(color=Color.BLACK)` you could do: `hub.light.off()`
- If the `kick` method is already working fine, then feel free to keep as is. But you may be able to kick even faster by using `track_target`, which skips any acceleration or speed setting and just goes to the target as fast as possible.

Coding suggestions:
- See the commits
- Mainly, I think we can keep the code a bit shorter by leaving out keyword arguments except where they are needed.
- I moved the initialization to the __init__ method. Feel free to move this back if that is not right.
- Within the class methods, I grouped some of the commands that do one thing, and added a short comment to that group.
- I added a wait to the while loop

For tricky basics, would it make sense to do it without a class altogether? That could be a good starting point for people who don't know how to use classes yet.

**Comment by TheVinhLuong102** [comment]
@laurensvalk thank you for the detailed comments. Let me walk these through with @AntoniLuongPham later today and/or tomorrow so that he understands what's going on. :)

> Many people might end up learning Python from your examples 👍

Yes! -- in my experience with @AntoniLuongPham, programming LEGO Robots has been a fantastic way to learn Python. Allow me to digress here and elaborate on our Python teaching & learning experience over the past 8-9 months.

While I understand the usefulness of visual coding interfaces such as Scratch, those interfaces are naturally limited in terms of expressing a number of powerful high-level concepts such as classes, reuse by inheritance, reuse by importing, etc. So I determined early on that @AntoniLuongPham should try to use Python to control the robots instead of taking the usual route of using Scratch/LabVIEW first, hitting a wall after a while, and then being forced to unlearn and learn something very different.

While his primary motivation is to make the robots do what he wishes, @AntoniLuongPham has also learned to enjoy the process of writing "nice" programs. It takes lots of time-consuming rinse-and-repeat for a young coder to develop a sense of what "nice" means for a page of austerely plain text on a black VSCode screen (in contrast, all Scratch programs are nice by default and instantly gratifying, because they are so colorful!). I would tell him "you've built a nice robot, so you should have your program look nice too!", and that would prompt him to spend more time finding ways to make the program a bit more structured, a bit more DRY (he doesn't know this term yet, actually), and a bit easier to explain when he records YouTube videos (big deal indeed! :D).

Writing and refactoring textual code also involves a lot more copying/cutting-and-pasting than in visual blocks-based coding, and I have observed very interesting abstract thinking seemingly developing behind his Ctrl-C/X/V hand movements. In the early days @AntoniLuongPham would copy and paste only extremely obviously repeating LOCs. Later on, he would copy and paste and modify blocks of multiple (3-5) commands. Then he would copy and paste whole functions or a few functions at a the same time, between programs. Then, as of now, he can confidently copy and paste a whole class or a whole file and modify it for a new robot (e.g. "I think this robot is quite like <Robot X>, so I'll copy the whole program there and delete what I don't need and add what more I need"). Obviously I cannot read his mind, but I think there're some very beneficial neural connections developing when the copy-and-paste activity takes place. And again, textual coding offers a lot more opportunities for such copying-and-pasting than visual blocks-based coding.

We do hope the Python examples we contribute would help other young coders to take up Python and reap these benefits too. :)

**Comment by TheVinhLuong102** [comment]
> we can keep the code a bit shorter by leaving out keyword arguments except where they are needed

On this point, I think we should strike a balance between brevity (and the performance benefits of such brevity on the SPIKE/Inventor Hub) and readability to the consumers of the examples. If we expect many Python beginners to read these examples, I feel "explicit is better than implicit" applies to a certain extent. Having keyword arguments at the right places would make it easier for young coders to know what those arguments are for. For example, `drivebase.drive(x, y)` is much less understandable than `drivebase.drive(speed=x, turn_rate=y)` to those who are new to the API.

One anti-pattern I can bring up is Robot Mesh's Python API for VEX Robotics (https://www.robotmesh.com/studio), which admits no keyword arguments at all. All of their functions have positional arguments only. I'm teaching VEX IQ with Python to middle-schoolers in my nonprofit work, and the positional-only API design has made it very painful to teach, learn and review each other's work.

So let me look at the updated Tricky programs and propose where I think some keyword arguments could be helpful. :)

**Comment by laurensvalk** [comment]
Thanks for your messages. I'm glad to see you're enjoying the learning process.

There are indeed some keyword arguments that would be useful to keep, but perhaps there is a right balance somewhere in the middle. For example, `left_motor=left_motor` or `color=Color.RED` are probably things we can avoid. I would also encourage to leave out keyword arguments which are the same as the default, such as `surface=True`. As in the commit above, sometimes a variable/constant can help too, e.g. `self.KICKER_SPEED`, but this depends a bit on the situation.

> which admits no keyword arguments at all

This was the case for Pybricks 1.0 too; we've been adding them ever since 2.0. In Python, you get keyword arguments automatically. When implementing MicroPython libraries in C, you have to do some extra coding such as parsing the arguments and validating their type. Besides the extra work it takes some extra flash, ram, and cpu resources.

Much you like said though, we totally think this is worth it, so we'll keep adding them when we add new functions.

**Comment by TheVinhLuong102** [comment]
> For example, left_motor=left_motor or color=Color.RED are probably things we can avoid. I would also encourage to leave out keyword arguments which are the same as the default, such as surface=True.

I totally agree -- those can and should be omitted. To make it simple to remember for @AntoniLuongPham, I have taught him to include all arguments explicitly. :) Now I'll step in and help make some judgement on explicit vs. implicit.

We'll try to finalize these programs following your suggestions by this weekend, including rewriting the Basic program without the class.

Btw, we should run linting checks (e.g. Flake8) on these programs as usual, right? In your latest code version, there's one long LOC flagged by the linters.

**Comment by laurensvalk** [comment]
> Btw, we should run linting checks (e.g. Flake8) on these programs as usual, right? 

That would be great, thanks. We're also open to suggestions to relaxing particular rules; they're not set in stone. They can be configured [here](https://github.com/pybricks/pybricks-projects/blob/master/setup.cfg). Especially if we're aiming for somewhat shorter scripts, maybe it does make sense to increase the maximum line length a bit, for example.

Since many users might use it in Pybricks Code, it would also be good to occasionally paste it there to get a feel for how it looks and works.

**Comment by AntoniLuongPham** [comment]
Dear @laurensvalk,

I have updated the Tricky basic and soccer programs according to your instructions.I have also tested the robot again and it works.

Thank you very much!

Antoni

**Comment by TheVinhLuong102** [comment]
@laurensvalk, as a checklist, the further changes @AntoniLuongPham has made are as follows:

> In reset_kicker_motor, I'm guessing you are using run_time to put the motor all the way to one end. You might want to consider run_until_stalled for this purpose
Done.

> If the kick method is already working fine, then feel free to keep as is. But you may be able to kick even faster by using track_target, which skips any acceleration or speed setting and just goes to the target as fast as possible.
Done.

> For tricky basics, would it make sense to do it without a class altogether? That could be a good starting point for people who don't know how to use classes yet.
Done.

At a few places, we have added back some keyword arguments to make the code a bit clearer to understand. :)

We will build and program other Tricky variants and submit new PRs, maybe from next weekend.

Thank you again!

Vinh

**Comment by laurensvalk** [comment]
Thank you! I’ll have a look as soon as possible.

I think you mentioned your YouTube channel a few times. Are you filming these robots as well? It might be pretty cool to have (short and mostly unedited) video snippets that show each demo program in action so people can see if they’ve done it right.

**Pull request merged**
