### PR TITLE
add Dinor3x and El3ctricGuitar (home bonus robots)

### PR DESCRIPTION
**Pull request by AntoniLuongPham**
Dear @laurensvalk and @dlech,

Please find my Dinor3x program submitted for your review.

I have enjoyed building and programming this robot very much. I like its walking by legs without wheels.

My Dad @TheVinhLuong102 helped me set up vscode files and reviewed my code and nagged me to do it properly. It took me lots of time (3 weeks).

Thank you for creating pybricks, I like it very much!

Antoni

### CODE REVIEW

**Comment by AntoniLuongPham** [comment]
Dear @laurensvalk and @dlech,

I have finished El3ctricGuitar for your review.

El3ctricGuitar is a short but fun program!

My Dad @TheVinhLuong102 helped me with some math and working with python lists.

Thank you very much!

Antoni

**Comment by laurensvalk** [comment]
Hi @AntoniLuongPham, thanks for your contribution! This is great.

**Pull request suggestions**

It would be great if you want to make a separate pull request per model. So feel free to open a new one for the Guitar, and just leave this one here. And if you don't mind, please use a different branch name for each one, such as `dinor3x`. It's easier for us to make changes that way :)

**Coding suggestions**

And as discussed in #7 , since the projects don't need to be a single file, I would perhaps consider moving/changing this section to a separate file

```python
    def main(self):
        self.close_mouth()

        while True:
            self.roar_by_ir_beacon()
            self.change_speed_by_color()
            self.walk_by_ir_beacon()


if __name__ == '__main__':
    DINOR3X = Dinor3x()
    DINOR3X.main()
```

So the Dinor3x class could be in `dinor3x.py` (without any "main"), and `main.py` would have something like this:

```python
from dinor3x import Dinor3x

dino = Dinor3x()

dino.close_mouth()

while True:
    dino.roar_by_ir_beacon()
    dino.change_speed_by_color()
    dino.walk_by_ir_beacon()
```

**Testing suggestions**
It would be great if you want to test your code one last time after it has been merged to make sure I didn't make any mistakes.

I suppose you have to take the model apart to build the next one, though. So if you make one PR per model and if I promise to do my best to merge them a bit faster, maybe this could work :)

**Comment by TheVinhLuong102** [comment]
@laurensvalk thank you for the detailed comments!

I'll help @AntoniLuongPham out with the Git branching because that's way beyond his comprehension right now. :) He's only been coding on his main branch, and kinda understands that his code there gets appended to his pull requests. Anyway I've seen some intuitive Git flashcards ("for dummies") somewhere on the web, so maybe this is an opportunity to up his Git skills then.

Apart from that, @AntoniLuongPham shall do the refactoring and follow up further. :)

P.S.: Every build-and-program round usually takes us 2-3 weeks, especially now that there's school homework to do as well. So indeed there's ample time for code review and revision in between. The El3ctricGuitar is an exception because the program is short (though not simple, because I did have to help @AntoniLuongPham figure out what the formulas and the lists do in the program).

**Comment by AntoniLuongPham** [comment]
Dear @laurensvalk, 
Thank you for your message!
I feel very happy today! :)

I updated my programs with the main.py files you told me to code.
My dad @TheVinhLuong102 also told me to do the READMEs.

I don't know how to do Git branch yet, so my dad will help me. 

Thank you very much! :)

Antoni @AntoniLuongPham

**Comment by TheVinhLuong102** [comment]
Hi @laurensvalk,

I have sit down with @AntoniLuongPham to guide him to:
- factor out the `.main(self)` methods and the `if __name__ == '__main__'` to the separate `main.py` files; and
- create proper `README.md` files, since there're multiple code files now and readers may find the docstrings hard to read.

@AntoniLuongPham tested running the `main.py` and ensured it ran successfully.

I notice you have just renamed the outer directory, so this PR will now have a conflict to resolve. Now I've realized it's a pretty bad idea for me and @AntoniLuongPham to initiate the PR from the `master` branch. :) For this PR, are you able to help us resolve the conflict and merge it? After the merge, we can resubmit the Guitar code in a separate PR from a new `guitar` branch.

Vinh

**Comment by laurensvalk** [comment]
Thank you for the updates!

> For this PR, are you able to help us resolve the conflict and merge it?

Sure thing!

> After the merge, we can resubmit the Guitar code in a separate PR from a new guitar branch.

Excellent. You could even do that already if you wanted to (that's another advantage of separate PRs).

**Comment by laurensvalk** [comment]
I merged it. Thanks again for your contribution.

Take your time with the Guitar, we are in no rush. In case the branches got a bit confusing, you can download this [ZIP file](https://github.com/pybricks/pybricks-projects/archive/4665636203c4caf7937a98faab540c0438e380c2.zip) of your original branch as a backup. The Guitar is in there too, so you could copy it into a new clean fork.

> I don't know how to do Git branch yet, so my dad will help me.

I didn't learn programming or Git until much, much later, so I'm very impressed with what you know already :smile:

**Comment by AntoniLuongPham** [comment]
Dear @laurensvalk,

Thank you for using my Dinor3x program!

My mum had me building the Dinor3x in this video: https://www.youtube.com/watch?v=KVgPFdRSSwE.

There is another video of me walking it to eat pumpkins for Halloween: https://www.youtube.com/watch?v=yKHT6Z5eR50.

I had to make the legs stronger by adding more beams and pins, because the legs were very weak and the Dinor3x fell down.

I hope you like the videos!

Antoni

**Pull request merged**
