### PR TITLE
Add Audi e-tron project and code for powered up remote control

### PR DESCRIPTION
**Pull request by tensafefrogs**
Hello, I have some code for the Audi e-tron set.

Fairly basic controls - details are included as comments in the main.py program.

Cheers!

### CODE REVIEW

**Comment by laurensvalk** [comment]
Thanks @tensafefrogs !

@legolasse , would you be interested to add your block-based program and/or video too?

**Comment by danacr** [comment]
can we please merge it?

**Comment by laurensvalk** [comment]
Thanks for the reminder @danacr, and thanks for becoming a project supporter!

I have also just added a block-based project for the Off-Road Truck, see below. I imagine the Audi E-tron project would be very similar. Probably just with different motor ports/directions/angles.

If you're interested in adapting and sharing the block project to the Audi, I would be happy to add it to the page.

[image](https://pybricks.com/projects/sets/technic/42099-off-roader/powered-up-remote/)

**Comment by laurensvalk** [comment]
No worries, if it's working for you that's fine :smile: 

In a block project, you can see the live preview of the Python code. Click the `</>` button to toggle it. But there isn't a conversion from Python to blocks.

**Pull request merged**
