### PR TITLE
add El3ctricGuitar program (home bonus robot)

### PR DESCRIPTION
**Pull request by AntoniLuongPham**
Dear @laurensvalk,

I am submitting El3ctricGuitar again for your review.

El3ctricGuitar is a short but fun program!

My sister Ariana likes its sounds and says it is very funny!

My dad @TheVinhLuong102 helped me with some math and working with python lists.

Thank you very much!

Next week I will program and build mr. B3am. It will count the holes and tell how long the beams are. it will also tell me the color.

Antoni

### CODE REVIEW

**Comment by laurensvalk** [comment]
Thanks @AntoniLuongPham !

@TheVinhLuong102 , for the next pull request, you may want to make a clean fork of `pybrick-micropython` to avoid complicated merges.

Then you can do, for example,

```
git checkout origin/master
git checkout -b mrb3eam
```

and work from there.

**Comment by TheVinhLuong102** [comment]
Hi @laurensvalk,

Yes I've noted and agree. Maybe we'll wait for existing PRs to settle before opening a new one, to reduce the possibility of complex merging.

**Comment by laurensvalk** [comment]
Thanks for the updates -- I've squashed them into a linear commit to avoid the multiple merges.

It would be great if you want to check if this all looks good and that it runs as intended on your Guitar.

Feel free to just download [this ZIP](https://github.com/pybricks/pybricks-projects/archive/cd14bd43aea46d260cff30501c46185bf5fcd216.zip) so you don't have to worry about the updated branch.

I'll merge it straight away when you confirm that all looks good.

**Comment by TheVinhLuong102** [comment]
@laurensvalk thank you for the squashing -- we have just checked it and it does run properly, so we are ready for the merge. :)

**Pull request merged**
