### PR TITLE
add Mr. B3am program

### PR DESCRIPTION
**Pull request by AntoniLuongPham**
Dear @laurensvalk and @dlech,

Please see and review my Mr. B3am program.

This robot is good and smart but Mr. B3am can only detect and measure accurately Black and Red Technic beams.

My dad help me with python strings and just a little bit of math and some doc strings.

I am going to make ev3_gam3 when I am done playing with Mr. B3am.

Thank you very much!

Antoni

### CODE REVIEW

**Review by dlech — CHANGES_REQUESTED** [review]
Looks good to me. Just a couple of minor suggestions.

**Comment by TheVinhLuong102** [comment]
@dlech thank you -- I've got @AntoniLuongPham to make those revisions. :)

By the way, we wrote similar programs using EV3Dev but couldn't get those to work: the Color detection is much less accurate in the EV3Dev programs than in the PyBricks program. May I check if you have done some additional "magic" somewhere wrt the ColorSensor in PyBricks?

**Comment by laurensvalk** [comment]
Thanks for adding this project!

>  May I check if you have done some additional "magic" somewhere wrt the ColorSensor in PyBricks?

We do, but only for the newer Powered Up sensors.

>  the Color detection is much less accurate in the EV3Dev programs than in the PyBricks program.

So I would expect that it performs about the same as on ev3dev.

It could be that using `reflection()` and `color()` together was a factor. Pybricks works around a hardware bug in the sensor to avoid problems when you do this.

**Comment by TheVinhLuong102** [comment]
@laurensvalk thank you. Could you reference some relevant issues/tickets for my understanding? Do `reflection()` and `color()` use 2 different modes and does the switching cause some data to be corrupt or go stale? What can we do to overcome such issues in EV3Dev?

**Comment by dlech** [comment]
https://github.com/ev3dev/ev3dev/issues/1401 has some in-depth information on the issue with the EV3 color sensor. Basically, the work around is to wait about 20 milliseconds after switching modes before reading the value to ensure that we don't get a stale value.

**Comment by TheVinhLuong102** [comment]
Thank you @dlech -- I'll follow that thread and related issues to understand better.

For EV3Dev-coded Mr. B3am, we'll revisit another time. Our young gentleman @AntoniLuongPham couldn't wait and has torn Mr. B3am apart and there's a construction site for EV3 Game for in our living room right this moment. :D

**Pull request merged**
