### PR TITLE
add Wack3m program

### PR DESCRIPTION
**Pull request by AntoniLuongPham**
Dear @dlech and @laurensvalk,

Please find my Wack3m program for your review.

This robot is not too hard to program but if we set some numbers too big or too small then the robot will not work well. My sister has a lot of fun playing with it.

My dad helped me with the complicated part that works with the IR Sensor. He also helped me with measuring the time and also find the right numbers.

Thank you very much!

Antoni

### CODE REVIEW

**Comment by laurensvalk** [comment]
Thanks Antoni!

Let's try tagging @martynboogaarts who designed this one. Who knows he wants to try it one day :smile:

**Comment by TheVinhLuong102** [comment]
Thank you @martynboogaarts! The Wack3m is a tricky one to program right -- you must have experimented a lot to find the right parameters for the game.

@AntoniLuongPham and I are very honored to connect with the Who's Whos of the LEGO community! :)

**Comment by martynboogaarts** [comment]
The original game was based on 2 things 
0 init all motors down 
1 I place the (random) mole up so I know what distance to look for the hammer
2 more or less in ranged place object (also a hand )  after putting the mole up counts as a correct hit (even if it was a miss) 
The average reaction time after 10 hits is what is counted and displayed 

I know it should be done better but within the limits of the toy that is what could be achieved 

Martyn Boogaarts

Op 6 dec. 2020 om 09:31 heeft Vinh Luong <notifications@github.com> het volgende geschreven:

﻿
Thank you @martynboogaarts! The Wack3m is a tricky one to program right -- you must have experimented a lot to find the right parameters for the game.

@AntoniLuongPham and I are very honored to connect with the Who's Whos of the LEGO community! :)

**Comment by TheVinhLuong102** [comment]
@martynboogaarts yes we know step (1) above was a lot of hard work. Thanks again for the game -- it was great fun and @AntoniLuongPham and his little sister played it for an entire week!

**Pull request merged**
